# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    working_directory: /app
    steps:
    # specify any bash command here prefixed with `run: `
    - run:
        name: "Create temp dir for artifacts"
        command: |
          mkdir -p /tmp/artifacts
    - run: go get -u all
    - run: go mod tidy
    - run:
        command: |
          go test -v -coverprofile=c.out -covermode=atomic ./...
          go tool cover -html=c.out -o coverage.html
          mv coverage.html /tmp/artifacts
          bash <(curl -s https://codecov.io/bash) -f c.out
    - store_artifacts:
        path: /tmp/artifacts